### ISSUE TITLE
Button icons are not showing

### ISSUE THREAD

**Issue by groenmarsmannetje** [rsnodgrass/water-heater-card#9]
The button icons are not displayed in HA version 2021.11.5

![image](https://user-images.githubusercontent.com/46958454/144441615-9a65d488-85c9-4b24-9ffd-454864f53e07.png)

**Comment by TheEris** [comment]
same

**Comment by Nicao** [comment]
same issue

**Comment by signingkd** [comment]
same issue

**Comment by rsnodgrass** [comment]
Thanks @rmanky!  Fixed.
